name: "Tests"
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Create artifacts directory
      run: |
        mkdir -p artifacts/artifacts
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Download Run Simulator
      run: |
        wget https://github.com/dfornika/illumina-run-simulator/releases/download/v0.1.0/illumina-run-simulator-0.1.0-standalone.jar -O illumina-run-simulator.jar
    - name: Create simulated run output directories
      run: |
        mkdir -p artifacts/artifacts/simulated_runs/{M00123,M00456,VH00123}/22
    - name: Run Run Simulator
      run: |
        timeout 10 java -jar illumina-run-simulator.jar --config .github/data/illumina-run-simulator/config.edn 2> >(tee artifacts/artifacts/illumina-run-simulator.log.jsonl) || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
        .github/scripts/add_qc_check_complete.py --simulated-runs-dir artifacts/artifacts/simulated_runs
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
