name: "Tests"
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Create artifacts directory
      run: |
        mkdir -p artifacts/artifacts
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Download Run Simulator
      run: |
        wget https://github.com/dfornika/illumina-run-simulator/releases/download/v0.1.0/illumina-run-simulator-0.1.0-standalone.jar -O illumina-run-simulator.jar
    - name: Simulate Runs
      run: |
        mkdir -p artifacts/simulated_runs/{M00123,M00456,VH00123}/22
        bash .github/scripts/simulate_runs.sh
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
